extends:
  - "airbnb-base"

overrides:
  -
    files:
      - "*.ts"

    extends:
      - "plugin:@typescript-eslint/recommended"

    rules:
      "@typescript-eslint/no-explicit-any": off
      "@typescript-eslint/ban-ts-ignore": off
      "@typescript-eslint/no-non-null-assertion": off
      "@typescript-eslint/interface-name-prefix": off

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

env:
  browser: true
  node: true
  jquery: true
  jest: true

globals:
  document: false

settings:
  import/resolver:
    webpack:
      config: "./config/webpack.common.js"

ignorePatterns:
  - "/docs"

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true

  no-new: off
  indent: off
  class-methods-use-this: off
  no-unused-expressions: off
  import/extensions: off
  lines-between-class-members: off
  no-console: off
