extends: "airbnb-base"

env:
  browser: true
  node: true

globals:
  document: false

settings:
  import/resolver:
    webpack:
      config: "./config/webpack.common.js"

ignorePatterns:
  - "/dist"

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
