extends: "airbnb-base"

env:
  browser: true
  node: true
  jquery: true

globals:
  document: false

settings:
  import/resolver:
    webpack:
      config: "./config/webpack.common.js"

ignorePatterns:
  - "/dist"

rules:
  no-unused-expressions: 0

  import/no-extraneous-dependencies:
    - error
    - devDependencies: true

  no-console:
    - error
    - allow:
      - error
