extends:
  - "airbnb-base"

overrides:
  -
    files:
      - "*.ts"

    extends:
      - "plugin:@typescript-eslint/recommended"

    rules:
      "@typescript-eslint/no-explicit-any": off

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

env:
  browser: true
  node: true
  jquery: true

globals:
  document: false

settings:
  import/resolver:
    webpack:
      config: "./config/webpack.common.js"

ignorePatterns:
  - "/dist"

rules:
  no-unused-expressions: off

  import/no-extraneous-dependencies:
    - error
    - devDependencies: true

  no-console:
    - error
    - allow:
      - error
